-- liquibase formatted sql

-- changeset aryazanov:1
CREATE TABLE IF NOT EXISTS animals
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    animal_name varchar(256) NOT NULL,
    age integer,
    animal_type varchar NOT NULL,
    CONSTRAINT pk_animal PRIMARY KEY (id)
);

-- changeset koledov:1
CREATE TABLE shelters
(
    id   SERIAL PRIMARY KEY,
    name TEXT
);